# Generated by Django 3.2.5 on 2021-07-28 06:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirConditioner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Device_ID', models.CharField(default=uuid.UUID('f0ef5b55-f832-4619-acfe-5a806e82c055'), max_length=100)),
                ('fig', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=100)),
                ('state', models.BooleanField(default=0)),
                ('temp', models.FloatField(default=0)),
                ('humidity', models.FloatField(default=0)),
                ('control_temp', models.IntegerField(default=0)),
                ('descriptuin', models.CharField(default='關閉', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='fan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Device_ID', models.CharField(default=uuid.UUID('18d6cae9-ad7d-4f40-8073-759c92bb2d2d'), max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('fig', models.CharField(max_length=300)),
                ('state', models.BooleanField(default=0)),
                ('descriptuin', models.CharField(default='關閉', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='light',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Device_ID', models.CharField(default=uuid.UUID('57205356-92f4-49a7-81c9-4fdb9cd01d19'), max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('state', models.BooleanField(default=0)),
                ('fig', models.CharField(max_length=300)),
                ('descriptuin', models.CharField(default='關閉', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='other',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Device_ID', models.CharField(default=uuid.UUID('a1a9adfc-534c-4f84-81b8-0d2477aa1e6c'), max_length=100)),
                ('fig', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=100)),
                ('state', models.BooleanField(default=0)),
                ('descriptuin', models.CharField(default='關閉', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='scene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SceneName', models.CharField(max_length=100)),
                ('Device_ID', models.CharField(max_length=100)),
                ('DoWhat', models.BooleanField(default=0)),
            ],
        ),
    ]
