# Generated by Django 3.2.5 on 2021-07-28 06:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airconditioner',
            name='Device_ID',
            field=models.CharField(default=uuid.UUID('073d4850-241d-4940-ba2f-451cdefdde9c'), max_length=100),
        ),
        migrations.AlterField(
            model_name='fan',
            name='Device_ID',
            field=models.CharField(default=uuid.UUID('0e52be98-6db1-4cf2-9ab4-3d8cc6c5b460'), max_length=100),
        ),
        migrations.AlterField(
            model_name='light',
            name='Device_ID',
            field=models.CharField(default=uuid.UUID('b84bef92-f2fc-4f25-ba5e-86a5ae122d99'), max_length=100),
        ),
        migrations.AlterField(
            model_name='other',
            name='Device_ID',
            field=models.CharField(default=uuid.UUID('034e96ab-b450-4af4-9bc0-4e8ffb66b659'), max_length=100),
        ),
    ]
