# Generated by Django 3.2.5 on 2021-07-28 07:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0003_auto_20210728_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airconditioner',
            name='Device_ID',
            field=models.CharField(default=uuid.UUID('4969d8b8-aa96-4e3d-b8ce-02baeef03989'), max_length=100),
        ),
        migrations.AlterField(
            model_name='fan',
            name='Device_ID',
            field=models.CharField(default=uuid.UUID('8a6d17f8-5854-440e-9ed7-e82f1ac44864'), max_length=100),
        ),
        migrations.AlterField(
            model_name='light',
            name='Device_ID',
            field=models.CharField(default=uuid.UUID('213f60a5-cda6-4437-a2a2-812e2345dfd9'), max_length=100),
        ),
        migrations.AlterField(
            model_name='other',
            name='Device_ID',
            field=models.CharField(default=uuid.UUID('e05613d7-3b4a-41ec-9388-6be8bde2cc60'), max_length=100),
        ),
        migrations.AlterField(
            model_name='scene',
            name='SceneName',
            field=models.CharField(max_length=500),
        ),
    ]
