# Generated by Django 3.2.5 on 2021-07-28 07:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0004_auto_20210728_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airconditioner',
            name='Device_ID',
            field=models.CharField(default=uuid.UUID('ac318eb6-3169-4e2b-a4d1-bf66808f5471'), max_length=100),
        ),
        migrations.AlterField(
            model_name='fan',
            name='Device_ID',
            field=models.CharField(default=uuid.UUID('3d31f3be-29d4-411a-af75-a317ea924d10'), max_length=100),
        ),
        migrations.AlterField(
            model_name='light',
            name='Device_ID',
            field=models.CharField(default=uuid.UUID('65b508ec-c660-4af2-a32b-22c29e417ac1'), max_length=100),
        ),
        migrations.AlterField(
            model_name='other',
            name='Device_ID',
            field=models.CharField(default=uuid.UUID('2fb1f7f3-b806-486e-bcfb-8d35057ff7b8'), max_length=100),
        ),
        migrations.AlterField(
            model_name='scene',
            name='SceneName',
            field=models.CharField(max_length=200),
        ),
    ]
