# Generated by Django 3.2.5 on 2021-07-28 07:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0005_auto_20210728_0701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scene',
            name='DoWhat',
        ),
        migrations.AlterField(
            model_name='airconditioner',
            name='Device_ID',
            field=models.CharField(default=uuid.UUID('d198faad-ae71-4f4d-b4f3-9ea3c90e6247'), max_length=100),
        ),
        migrations.AlterField(
            model_name='fan',
            name='Device_ID',
            field=models.CharField(default=uuid.UUID('bf6b6428-1a62-441a-91b5-7685d1daeeb5'), max_length=100),
        ),
        migrations.AlterField(
            model_name='light',
            name='Device_ID',
            field=models.CharField(default=uuid.UUID('83a85bf0-ebea-48de-a2e5-c938dc9a4e91'), max_length=100),
        ),
        migrations.AlterField(
            model_name='other',
            name='Device_ID',
            field=models.CharField(default=uuid.UUID('bdd541c5-6c53-4347-a136-dbce1d7d13e1'), max_length=100),
        ),
    ]
