# Generated by Django 3.2.5 on 2021-07-28 07:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0006_auto_20210728_0707'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Device_ID', models.CharField(default=uuid.UUID('e31f1c18-3d81-4772-9229-bf97208e4580'), max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('state', models.BooleanField(default=0)),
                ('fig', models.CharField(max_length=300)),
                ('descriptuin', models.CharField(default='關閉', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='AirConditioner',
        ),
        migrations.DeleteModel(
            name='fan',
        ),
        migrations.DeleteModel(
            name='light',
        ),
        migrations.DeleteModel(
            name='other',
        ),
    ]
