# Generated by Django 3.2.5 on 2021-07-28 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0007_auto_20210728_0734'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Device_ID', models.CharField(max_length=200)),
                ('value', models.FloatField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='device',
            name='Device_ID',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='device',
            name='state',
            field=models.BooleanField(),
        ),
    ]
