# Generated by Django 3.2.5 on 2021-07-29 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0009_auto_20210728_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='automation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('automation_name', models.CharField(max_length=200)),
                ('sensor_condition', models.CharField(max_length=200)),
                ('OpenDevice_ID', models.CharField(max_length=100)),
                ('closeDevice_ID', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='timer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timer_name', models.CharField(max_length=200)),
                ('time', models.DateTimeField()),
                ('OpenDevice_ID', models.CharField(max_length=100)),
                ('closeDevice_ID', models.CharField(max_length=100)),
            ],
        ),
    ]
