# Generated by Django 3.2.5 on 2021-07-29 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0010_automation_timer'),
    ]

    operations = [
        migrations.AddField(
            model_name='automation',
            name='Enable',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timer',
            name='Enable',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
